name: Release

on:
  workflow_dispatch:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set version env
        run: echo "CI_VERSION=$(cat server/res/version.txt | awk NF)" >> $GITHUB_ENV
      - name: Set date env
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Prepare Docker Hub Readme
        run: cat docker-readme.md | sed "s/{{version}}/${CI_VERSION}/g" | sed "s/{{date}}/${TODAY}/g" > docker-readme-modified.md
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: easypointment
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: CI_VERSION=${{ env.CI_VERSION }}
          context: ./booking-ui
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            easypointment/booking-ui:${{ env.CI_VERSION }}
            easypointment/booking-ui:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: CI_VERSION=${{ env.CI_VERSION }}
          context: ./admin-ui
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            easypointment/admin-ui:${{ env.CI_VERSION }}
            easypointment/admin-ui:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            easypointment/backend:${{ env.CI_VERSION }}
            easypointment/backend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: easypointment
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
          repository: easypointment/backend
          readme-filepath: ./docker-readme-modified.md
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CI_VERSION }}
          release_name: ${{ env.CI_VERSION }}
          draft: false
          prerelease: false
